# reconstruction of parameter values that are different between the PDF
#  defaults and what was dumped from the chip on Jan 14, 2022

Channel_.*:
  Inputdac: 0
  Dacb: 0

CM.*:
  Inputdac: 0
  Dacb: 0

CALIB.*:
  Inputdac: 0
  Dacb: 0

Reference_Voltage_.*:
  Inv_vref: 224
  Noinv_vref: 160

Global_Analog_.*:
  ON_dac_trim: 0
  ON_conv: 0
  ON_pa: 0
  Gain_conv: 0b1000
  Dacb_vb_conv: 0b100000
  Dacb_vbi_pa: 0b110000
  Sw_Cf_comp: 0b1110
  En_hyst_tot: 1
  Sw_cd: 0b001
  Sw_Rf: 0b0101
  Sw_Cf: 0b0100
